branch-defaults:
  develop:
    environment: blogEnvAws-env
  master:
      environment: blog-production
environment-defaults:
  blogEnvAws-env:
    branch: null
    repository: null
global:
  application_name: blog-env-aws
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/Passenger with Ruby
    2.3 running on 64bit Amazon Linux/2.4.0
  default_region: ap-south-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
